package org.example.services;

import jakarta.annotation.PostConstruct;
import org.example.entity.Speaker;
import org.example.entity.Tyre;
import org.example.entity.Vehicle;
import org.example.repositories.Inventory;

public abstract class VehicleService {
    private TyreService tyreService;
    private SpeakerService speakerService;
    protected Inventory inventory;

    protected VehicleService(TyreService tyreService, SpeakerService speakerService,Inventory inventory) {
        this.tyreService = tyreService;
        this.speakerService = speakerService;
        this.inventory = inventory;
    }
    public Inventory getInventory() {
        return inventory;
    }

    /**
     * Five vehicles objects are created by the constructor of Vehicle class.
     * Tyre and Speaker are generated by TyreService and SpeakerService.
     * Vehicles are added to vehiclesList.
     * */
    @PostConstruct
    public void generateVehicleList() {
        for (int i = 1; i <= 5; i++) {
            Tyre tyre = tyreService.generateTyre();
            Speaker speaker = speakerService.generateSpeaker();

            int vehiclePrice = tyre.getPrice() + speaker.getPrice() + (int)generateRandomPrice();

            Vehicle vehicle = new Vehicle(speaker, tyre, vehiclePrice);
            inventory.addVehiclesToList(vehicle);
        }
    }
    public abstract double generateRandomPrice();
}
